import type { Metadata } from "next";
import { Space_Mono, JetBrains_Mono, Roboto_Mono } from "next/font/google";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import Navbar from "./components/ui/Navbar/Navbar";
import LenguageButton from "./components/ui/LenguageButton/LenguageButton";

const spaceMono = Space_Mono({
	variable: "--font-space-mono",
	weight: ["400", "700"],
	subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
	variable: "--font-roboto-mono",
	weight: ["200", "300", "400", "500", "600", "700"],
	subsets: ["latin"],
});

const jetbrainsMono = JetBrains_Mono({
	variable: "--font-jetbrains-mono",
	weight: ["200", "300", "400", "500", "600", "700"],
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${spaceMono.className} antialiased`}>
				{
					<NextIntlClientProvider>
						<Navbar>
							<LenguageButton />
						</Navbar>
						{children}
					</NextIntlClientProvider>
				}
			</body>
		</html>
	);
}
